### ISSUE TITLE
point: overload the << operator 

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#100]
First, read this: https://github.com/mo-c/moses-cpp-learning/wiki/Operator-overloading

Once you have a basic idea of what operator overloading is, then try to overload the << operator so that it is able to push Point instances to the standard output stream.

It should basically print the x and y coordinates inside a pair of brackets. That is, if you have a Point called myPoint that has an x-coordinate of -5 and a y-coordinate of 12, then the statement

    std::cout << "The point is at: " <<  myPoint << std::endl;

Should print out

    The point is at: (-5, 12)

**Comment by lcabrini** [comment]
Have you tried this out yet?

**Comment by mo-c** [comment]
There is a place where it says i should declare the overloading in the .h file without making it part of the class. How do i do that?

**Comment by lcabrini** [comment]
You place the declaration outside of the class Point { } block. But it makes most sense to place it after, since you are referring to Point in the operator declaration.

**Comment by mo-c** [comment]
Have you checked the codes I sent? I will make that correction soon
