### ISSUE TITLE
straight-line: implementation of line_is_horizontal is indefinately recursive

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#103]
Inside the function line_is_horizontal you make a call to this same function. This is going recurse until you run out of stack space.

What you want to do instead is check if y1 == y2. If that is true, then the line is  horizontal. Otherwise it is not.

In summary, the name of the function is line_is_horizontal(). Its job is to take two y-coordinates and check if they are equal. If they are, return true, otherwise return false. Client code (that is code in main() will call line_is_horizontal() to find out if a given line is horizontal or not.

**Comment by mo-c** [comment]
I am confused about how to use the line_is_horizontal.

**Comment by mo-c** [comment]
I am having problem with my password when i want to git push

**Comment by lcabrini** [comment]
Regarding the password, are you pushing via ssh or https? If it is ssh then it should be the passphrase that you used for you ssh public key. Otherwise I think it should be your github password.

**Comment by lcabrini** [comment]
Here is an implementation of line_is_horizontal():

    bool line_is_horizontal(double y1, double y2)
    {
        if (y1 == y2) {
            return true;
         } else {
             return false;
        }
    }

Take notice of the following:

1. The name of the function is explanative of what the function does: it is line_is_horizontal
2. The function takes two arguments, y1 and y2. It needs these to be able to do its job. This information comes from an external source (the main function) so you will have to pass them into the function.
3. The functions return type is bool, because the function will return true of false. Either the line is horizontal or not. There are no other possibilities.
4. Inside the function body, we just compare the value of y1 and y2. That is the way to determine whether or not the line is horizontal. If y1 and y2 are the same, the line is horizontal, otherwise it is not.

**Comment by mo-c** [comment]
It's the pass phrase is asking for and I can't remember.  Please send me
the branch of Ecobank?

**Comment by lcabrini** [comment]
Actually, you should have created a new issue for the passphrase, because we are now hijacking an issue related to line_is_horizontal. And let's talk about personal issues outside of github.

If you can't remember your passphrase you have to create a new ssh key and upload it. There is no other way
