### ISSUE TITLE
straight-line: bad call to line_in_horizontal()

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#106]
The call to line_is_horizontal() is not correct.

1. It must be called at the right place. Try to figure out at exactly which point in the code it would make sense to find out if the line is horizontal.
2. You are assigning the return of line_is_horizontal to a variable called y, which is a double. But the function returns a boolean, not a double. The function returns true if the line is horizontal or false if it is not.
3. The name of the variable y does not make sense at all in this context. It would be expected that y is to hold a y-coordinate, but line_is_horizontal does not return a coordinate, it returns true or false.

**Comment by mo-c** [comment]
I think it will be better after all the coordinates have been entered

**Comment by lcabrini** [comment]
yes, of course. It should be when you are building the equation. look at the code carefully and you will see where to slot the call in.

**Comment by mo-c** [comment]
I got it. It should at the end. Is it correct?

**Comment by lcabrini** [comment]
Let's look at how in general we figure out and print the straight line equation:

1. It the line vertical? If so print x = C, where C is known.
2. Otherwise, is the line horizontal? If so print y = C, where C is known.
3. Otherwise, calculate the gradient and the intercept and print out the equation in the format y = mx + b.

There, that is all you need. The answer is right in front of you.

**Comment by mo-c** [comment]
Is the C from your comment the same as  b in mine. Also i have been  trying so many ways to call the boolean function but to no avail.

**Comment by lcabrini** [comment]
A boolean can either be assigned to a variable or used in an if expression:

    if (line_is_horizontal(y1, y2)) {
        // code to execute if the line is horizontal
    }

**Comment by mo-c** [comment]
I have done the function. I am sure you can see it. My challenge now is how
to call it in the main.

**Comment by lcabrini** [comment]
The code I just wrote was meant to be in main(). You are calling the line_is_horizontal() function from there, getting the return value (true or false) and acting on it.

**Comment by lcabrini** [comment]
No, C in my comment is NOT b in your code. In your code, you use b to signify the intercept that the line makes with the y-axis.

When I used C in my previous comment I was referring to a constant, which you will have in the case of a horizontal or a vertical line. For a horizontal line, the equation will be of the form y = C, since for any x, y will have the same value. In the case of a vertical line, the equation is x = C, since any value of y corresponds to a constant x. 

That is completely different from the equation y = mx + b which is the form the equation will take when it is neither horizontal nor vertical.

**Comment by lcabrini** [comment]
This issue seems solved. Please close it.
