### ISSUE TITLE
point: put brackets around coordinates in << overloading

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#109]
In the implementation of the << operator for a point, add brackets around the coordinates. It is customary to write a pair of coordinates in the form (x, y), e.g. (5, -7).

**Comment by mo-c** [comment]
is it in the point .cc file or main.cc. I don't seem to see where to put it.

**Comment by mo-c** [comment]
i don't have anything like that in the point.cc where it seems the implementation is.

**Comment by lcabrini** [comment]
You do. Just that you are not including the brackets.

    std::ostream& operator<<(std::ostream& out, const Point& p)
    {
        return out << p.x() << " , " << p.y();
    }

All you need to do is add the brackets around the coordinates.

**Comment by mo-c** [comment]
std::ostream& operator<<(std::ostream& out, const Point& p)
{
    return out <<( p.x() << " , " << p.y());
}

will it be like this?

**Comment by lcabrini** [comment]
the brackets are supposed to be part of the output, which means that they are string literals. That in turn means they have to be quoted.

**Comment by mo-c** [comment]
But the position of the brackets are correct.

**Comment by lcabrini** [comment]
yes. the position is ok. but remember that you will also have to add stream operators (<<) at the right places.

**Comment by mo-c** [comment]
I am still having error about the endl part

**Comment by lcabrini** [comment]
Hm.. there should be no endl here. This is just to push a point onto a stream. std::endl should only be added when you are using cout inside main().

**Comment by mo-c** [comment]
Still having error

**Comment by lcabrini** [comment]
Could you copy the error message? Or do a push, without closing the issue. You could add this to your commit message:

refs #109

That way, it references this issue, without closing it. Makes it easier to track what we are  working on but doesn't close issues that are not completed yet.

**Comment by mo-c** [comment]
I have git pushed it.

**Comment by lcabrini** [comment]
It should be:

    return out << "("  << p.x() << ", " << p.y() << ")";

You need to close the quotes properly and remove the trailing <<.

**Comment by mo-c** [comment]
okay

**Comment by mo-c** [comment]
still having errors

**Comment by mo-c** [comment]
i have git pushed it.

**Comment by lcabrini** [comment]
but is it working? because if it is, you should close the issue

**Comment by mo-c** [comment]
no giving me some errors

**Comment by lcabrini** [comment]
Sorry, my fault. Little mistake there. Because p is not a Point but a reference to a point, you cannot use p.x() and p.y(). Instead you have to use p->x() and p->y().

    return out << "("  << p->x() << ", " << p->y() << ")";

I think tiredness is preventing me from seeing these things. :(

**Comment by mo-c** [comment]
i have more errors now

**Comment by lcabrini** [comment]
hm.. push again then.

**Comment by mo-c** [comment]
i have

**Comment by lcabrini** [comment]
Comparing to my own code, I used Point* p instead of Point& p in the funtion prototype.

**Comment by mo-c** [comment]
it should work the same way

**Comment by lcabrini** [comment]
hold on. my implementation is different. give me a few minutes to work this out.

**Comment by lcabrini** [comment]
Sorry, change. Point& p should stay. The calls should stay p.x() and p.y(). (Your implementation is a bit different from mine).

What you need to do is declare the functions x() and y() const. So in point.h

    double x() const;
    double y() const;

Just add the const keyword after the declarations of these two functions. Also in point.cc you need to add this for the two.

    Point::x() const {

    Point::y() const {

Man I'm so tired I can hardly think any more. Hope you can make sense of all this at this point. Will have to explain this tomorrow. Please remind me, I don't think I'll remember any of what has happened this evening in the morning.

**Comment by mo-c** [comment]
okay
