### ISSUE TITLE
line: declaration of operator== in line class

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#113]
In order to compare, you will need to lines. The declaration should thus be:

    bool operator==(const Line& lhs, const Line& rhs)

The names lhs and rhs are conventional in C++ and refer to left hand side and right hand side, meaning on line comes to the left of the ==, the other to the right.

**Comment by mo-c** [comment]
is this declaration unique to == operator?

**Comment by lcabrini** [comment]
No, not only to the == operator, but some other operators as well, such as +, -, * and /. Yes, they can all be overloaded. We'll look at more examples.
