### ISSUE TITLE
makefile missing in arearect directory

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#14]
Once you figure out how makefiles work, you should include the makefile in the commit. So for example, in this case you would have createed arearect.cc and Makefile. You should then proceed with:

% git add arearect.cc Makefile
% git commit

**Comment by mo-c** [comment]
But i am not getting the make file. After creating the make file how to compile it. i used just make  and it is not working

**Comment by lcabrini** [comment]
Fix the other makefile first (issue #2). Then come back and fix this issue.
