### ISSUE TITLE
create program: point

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#18]
You should first create a class Point, which represents a point on a coordinate system. It should have the following methods:

- x()
- setX()
- y()
- setY()

Then write a program that creates two points, and prints their coordinates.

**Comment by mo-c** [comment]
I have an for error that i don't understand. Please look into it for me.

**Comment by lcabrini** [comment]
You have several issues. Let me open an issue for each one of them so that we stick to what we have been doing so far.
