### ISSUE TITLE
Remove "using namespace std" from C++ source files

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#19]
Up to now you have used using namespace std with your standard library includes. This is convinient in the beginning and when you just want to write some quick code. But it is time to get used to preceding standard library calls with std:: instead. 

Namespaces are a good thing in C++. It allows you to create your own functions without worrying too much if something with that name already exists. The problem is that when you use the namespace std, you are practically pulling in all the standard library functions into your application's namespace. This is not really a good practice, so let's stop it.

Update all your source files so that:
1. you remove the statement using namespace std after the includes
2. you prefix all symbols from the standard library with std::, std::cout, std::endl

Update all your source files, then add them all to your git commit. That is you will first modify all the files, then you will add them all.

% git add areatri/main.cc arearect/main.cc hello/main.cc

then commit

**Comment by mo-c** [comment]
while changing the namespace to st:: i had a problem with the xtable was showing error with the setw part of the code

**Comment by lcabrini** [comment]
Yes, you need to procede it with std:: as well. It should be std::setw.

It takes a while to get used to always putting std:: in front of everything. However, the long term benefit is that you keep all the standard build-in functions and classes inside the std namespace. That is a big benefit once you start working on slightly larger stuff, since it means that you are going to avoid naming clashes. 

The using namespace std is convenient for beginner C++ programmers, and also when you just want to write some quick prototype code and save a little bit of time. But you should avoid it as much as possible from this moment on.
