### ISSUE TITLE
Add makefile to hello app

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#2]
The makefile should be called Makefile (notice capital M). it should reside in the hello folder.

For now, a really simple Makeifle could look as follows:

all:
        c++ main.cc -o hello

**Comment by lcabrini** [comment]
I should add that once you have a makefile, you can compile typing either make or gmake, depending on your platform

**Comment by mo-c** [comment]
I typed the make file as you said but it did not work.

i called the file Makefile.cc. in the same folder as hello Is that correct?

**Comment by lcabrini** [comment]
No, the makefile should just be Makefile. Remove the .cc and try again.

**Comment by mo-c** [comment]
I have changed it to Makefile. 
Which one do i use to compile, make, gmake

**Comment by lcabrini** [comment]
With a makefile this simple I don't think it matters. But, try one, if it doesn't work try the other.

**Comment by mo-c** [comment]
it says missing separator. stop.

**Comment by lcabrini** [comment]
Makefile syntax is a bit quirky with indentation. You *must* use tab for indentation. So, this is how you should type it:

all:
<TAB>g++ main.cc -o main
