### ISSUE TITLE
Update .gitignore to ignore vim swap files

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#23]
Inside your project directory you will always have some files that you don't want git to track, such as .o files, and so on. In the project folder you can have a file called .gitignore which tells git to ignore certain files that follow certain patterns.

You already have a .gitignore in your project folder. It was created by github when you set up the project. This is a default .gitignore, useful for C++ projects. However, it does not ignore vim swap files, so you  need to update it.

A vim swap file is like a state file that is created by vim while it has a particular file open. The state file begins with a dot, followed by the name of the file you are editing followed by .swp. So a generic pattern for all swap files is:

.*.swp

Update the file .gitignore in your project folder (notice that the file name starts with a dot). It will already contains quite a few lines. Go to the bottom and add a new ilne, typing simply: .*.swp

**Comment by mo-c** [comment]
do i create a folder in the project folder.Since the project folder has different folders for different projects or do i create a separate folder in the project folder?

**Comment by lcabrini** [comment]
No, just edit the .gitignore file in the root directory of the project, that is moses-cpp-learning.

Later, you can add overrides in subfolders, but we shall get to that later.

**Comment by mo-c** [comment]
Where will i find the .gitignore file?

**Comment by lcabrini** [comment]
In the project root folder (moses-cpp-learning)

**Comment by mo-c** [comment]
In the project folder I have all the folders for the individual project. I
can not see the .git ignore

**Comment by mo-c** [comment]
Do i do vim root? and them type the swap file

**Comment by lcabrini** [comment]
no, be in the project root folder. Then vim .gitignore
