### ISSUE TITLE
Create a wiki page on make

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#25]
Go to the project wiki (right hand side of your screen) and create a page called "Notes on make". Use this page to take notes as you learn new things about make. This will allow you to have a reference to go back to.

You can also add other wiki pages as you see fit. If you open an issue for each page you intend to create, that serves as a todo list that you can come back to later. Also, it follows the workflow of "only work on issues in the issue queue".

**Comment by mo-c** [comment]
How to i commit what i do only on git hub and from a command line.

**Comment by lcabrini** [comment]
You mean related to the wiki? On github, there should be a field for commit message. If you want to work on the wiki locally there is a way to clone your proejct's wiki repository, but I cannot remember it. I'll find it.
