### ISSUE TITLE
constant x crashes straight-line

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#29]
I used the following values:
x1: 7
y1: 0
x2: 7
y2: 9

The program crashed with the following message:
zsh: floating point exception  ./equation

**Comment by lcabrini** [comment]
I think you should relabel this one as a bug, because it was the only test I did that actually crashed the program.

**Comment by mo-c** [comment]
i changed the data type to float and it gave infinity, which is correct

**Comment by lcabrini** [comment]
Yes, it is. Because newer version of C++ support inf and -inf for double types. However, when the line is vertical, you don't really state the equation in terms of y but instead in terms of x. So the output in this case should be

x = <constant value>

so in the case above, I should have got the output:

The equation of the straight line is: x = 7

**Comment by mo-c** [comment]
I did not get the solution . Which output, i changed the y to x but the result still remains

**Comment by lcabrini** [comment]
No, just take one of the two x values. They are the same, that is why the line is vertical. so y = x, but the value of x you will use is either x1 or x2.

**Comment by mo-c** [comment]
The solution did not work.

**Comment by lcabrini** [comment]
There are several different conditions you need to work out. If you don't do them in the right order, it will not work,
