### ISSUE TITLE
Format of equation for a horizontal line

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#30]
When I enter coordinates for a horizontal line such as:
x1: 0
y1: 9
x2: 10
y2: 9

It gives me the following output:
The gradient of the line is :0
The intercept of the line is : 9
The equation of the line is :y =0x+9

Which is correct, but the convention is usually not to write
y = 0x + 9
but rather just 
y = 9

**Comment by mo-c** [comment]
I have tried a lot of methods on this one but could not solve it.

**Comment by lcabrini** [comment]
Well, one way to do it is to check if y1 == y2. If it is. print the shorter equation. Like so asuming (gradient = g and intercept = b)

    if (y1 == y2) {
      std::cout << "y = " << b << std::endl;
    } else {
      std::cout << "y = " << g << "x + " << b << std::endl;
    }

**Comment by lcabrini** [comment]
Or, you could also have tested if the gradient was 0 instead. The rest of the code would be the same

    if (g == 0) {
        ...
    } else {
        ...
    }

**Comment by mo-c** [comment]
i did just that, but the result is still the same. i will push the code for you to see.

**Comment by lcabrini** [comment]
It is fine for you to push the code, but please avoid closing te issue. The issue should remain open until you have fixed it.

**Comment by lcabrini** [comment]
It seems I cannot re-open this issue. Please re-open it so that it remains open until the issue is fixed.

**Comment by lcabrini** [comment]
Also I don't seee this code anywhere. There is nowhere where you are comparing y1 and y2. You have three main options:
1. the line is horizontal
2. the line is vertical
3. the line is diagonal

For the first two, you will get an equation of the type y = c or x = c depending on whether or not it is horizontal or vertical. For option (3) you have the following options as well.
(1) x = 1, in which case you write x, not 1x
(2) b = 0, in which case you write y = mx, not y = mx + 0
(3) both x = 1 and b = 0 in which case you write y = x, not y = 1x + 0

You have to work out the logic here. You will need to use two different if statements. One is embedded in the other.

**Comment by lcabrini** [comment]
Remember that as you are working on this issue, that you *only* need to  calculate m and b if and only if the line is diagonal. For horizontal and vertical lines, there is no need and no point in calculating them. Why? Because.

(1) for a horizontal line, m is always 0. b is going to be the value of y1 or y2 (they are the same).
(2) for a vertical line, m is always inf or -inf. So you cannot describe the equation in terms of y, but only in terms of x. m is going to be the value of x1 or x2 (they are the same)
