### ISSUE TITLE
Format of equation when gradient is 1

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#32]
It is not wrong to print the equation as
y = 1x + 3
But maybe it would be a little more conventional to print it as
y = x + 3

**Comment by mo-c** [comment]
i used 

else if(m==1)
{
     cout << "y = x + " << b<< endl;
}

i am right.

**Comment by lcabrini** [comment]
Yes, that looks correct.

**Comment by mo-c** [comment]
i used it but it is not working

**Comment by lcabrini** [comment]
You must make sure that you put this in the right place in the code. Please re-open issue #30, because I made quite a few comments there. (I also opened an issue about this)

**Comment by mo-c** [comment]
how do i re open issue #30

**Comment by mo-c** [comment]
can i use else, else if and then use if again?

**Comment by lcabrini** [comment]
To reopen the issue, click here: #30 
Then go to the bottom and click on the reopen issue button

**Comment by lcabrini** [comment]
Finish solving the first part of the problem as outlined in https://github.com/mo-c/moses-cpp-learning/wiki/Straight-line-equation

Then come back to this issue
