### ISSUE TITLE
askname does not behave according to specification

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#37]
You must always run basic tests on your programs before you commit and close an issue. That is your responsibility. In a real-world situation, you'd be expected to do this. Here you are learning, so you can make mistakes along the way. 

The program should do two things:
(R1) if the user types their name, greet them
(R2) if the user doesn't type anything, print "howdy, coward"

This means you should run the program with at least two tests:
(T1) enter a name, eg. Jimmy
(T2) hit enter immediately without typing anything

To be a bit more exhaustive, I would add a two more tests:
(T3) enter a longer name, eg. Billy Bones
(T4) press space once or twice then hit enter

If T1-T4 represent your tests, then you should run them *every time* you make a change to your code. YOu never know, something that used to work may break. Often, code you write may have unexpected side effects.

If you had tested the code, you would have noticed that only T1 passes properly.

T2 and T4 fail because of the way the >> works. After the failing these tests, you should have followed up with a comment saying that the program doesn't work according to the way it should. This would have been a good moment for me to introduce get getline().

T3 wasn't really covered by the specification at all, but it still an example of somewhat odd behavior. For this issue, you should have opened a new issue. The issues title could be sometihng like "askname: part of the input is cut off" with a more detailed explanation in the comment.

All of T2-T4 can actually be solved by the same change. But I have to teach you. Run the tests on your own machine and state which tests fail for you. Then you can close this issue an open a new one. We'll deal with the issue there.

**Comment by mo-c** [comment]
To be honest i did tested it, but could not fix the problem.

**Comment by mo-c** [comment]
sometimes i will think so hard but still will not be able to find a solution to it.

Maybe you should let me know when there is the need for a new concept.

**Comment by lcabrini** [comment]
That is good, but you should have reported that to me and not just closed the issue. The fact is that with >> you will not really be able to solve it. So I wanted you to report back so that we can use that as an introduction to getline() and what it does.

It is cool, however, because this is the way you will learn best. Just bear in mind the proper testing procedure.

Sometimes I will show you when there is a need for a new concept, but sometimes not. :)

**Comment by lcabrini** [comment]
take a look at this wiki page that I created:
https://github.com/mo-c/moses-cpp-learning/wiki/Reading-input-with-getline()

**Comment by lcabrini** [comment]
Use the information in the wiki page to fix this issue

**Comment by lcabrini** [comment]
By the way, this will not solve T4. But T4 was *not* a part of the original specification. I may add an issue for that at a later stage.
