### ISSUE TITLE
new app: temperature

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#42]
Write a program that first asks the user which temperature scale they want to enter the temperator in. The valid choices should be: celsius, kelvin and fahrenheit. Next the program should ask the user to enter the temperature.

The program should convert the temperature into the other two temperature scales and print these value out.

**Comment by mo-c** [comment]
Are you trying to test for functions in this exercise?

**Comment by lcabrini** [comment]
you *could* solve it without functions, but bit by bit I want you to start using functions to help. So, yes, I prefer that you use functions where possible

**Comment by mo-c** [comment]
Okay
