### ISSUE TITLE
create app: or-table

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#50]
the program should output a table for logical or

**Comment by mo-c** [comment]
i don't understand this exercise

**Comment by lcabrini** [comment]
The program should print out a truth table for logical OR. The result is true when at least on the operand is true. You can use two operands, a and b. The result should be:


    % ./or-table 
            A|       B|  A OR B
     --------+--------+--------
            0|       0|       0
            0|       1|       1
            1|       0|       1
            1|       1|       1

We shall take 0 to represent a false value and 1 to represent a true value. If you want, you could change it to output true and false or T and F instead.

**Comment by mo-c** [comment]
I am having difficulty on how to use the for loop for strings like  A, B, A or B
