### ISSUE TITLE
point: missing implementation of point methods

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#54]
The methods in the Point class have been declared but not implemented. You need to implement them.

**Comment by mo-c** [comment]
i really don't know how to implement the methods

**Comment by lcabrini** [comment]
In the declaration you have declared a method 

    int get_x()

Now you need to provide an implementation. That is the actual method. It may look as follows:

    int Point::get_x()
    {
        return m_x;
    }

You need to do the same for all the methods that you have declared.
