### ISSUE TITLE
point: set_x() and set_y() take both x and y coordinates

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#55]
setX() should be used to set the x-coordinate and setY() should be used to set the y-coordinate. As it is now, set_x() and set_y() each requires an x and a y value.

**Comment by mo-c** [comment]
guide me on this exercise so i can begin to understand the principles behind it.

**Comment by lcabrini** [comment]
There are two functions setX() and setY(). The setX() function should be used to change the value of x, and setY() should be used to change the value of y. However, right now, *both* setX() and setY() take an x and a y parameter. What you should have is

    void setX(double x);
    void setY(double y);

If you don't do this, then you should rather have a function:

    void setXandY(double x, double y);

However, you should avoid this, because in OO we normally have one accessor/mutator per attribute in the class.

**Comment by lcabrini** [comment]
Please look at this for a simple introduction to classes: https://github.com/mo-c/moses-cpp-learning/wiki/Creating-a-class
