### ISSUE TITLE
Point move point declaration/implementation into separate files

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#58]
Although it is not required, it is normally good practice to split your code into multiple source files. The declaration of the Point class should go into point.h, the implementation into point.cc. The file main.cc should mostly just contain the main() function and possibly the odd utility function.

**Comment by mo-c** [comment]
I would have love to understand functions very well before moving into
classes and then to splitting of the codes.

**Comment by lcabrini** [comment]
I understand what you mean, but classes have methods which really are functions. And this is likely to help you understand functions better.

However, if you want to keep it all in a single file for now, that is fine. Just leave this issue open so that you can come back to it when you are ready.

**Comment by lcabrini** [comment]
For some info, look here: https://github.com/mo-c/moses-cpp-learning/wiki/Creating-a-class

**Comment by mo-c** [comment]
I have separated the code into files but i am getting some errors. Please check it for me.

**Comment by lcabrini** [comment]
Well point.cc compiles fines for me. The problem comes when trying to compile main.cc. The error messages make it quite clear what the problem is.

1. You are trying to call functions set_x() and set_y(), but you forgot the brackets at the end of them. With functions you must have () there, even if the argument list is empty.
2. You are calling set_x() and set_y(), but these are the mutator methods. They should be used to change the values. Here you want to access the values in order to print them out. You should be using the accessor functions, not the mutators.

Fix those issues and you should be fine.
