### ISSUE TITLE
point: missing method declarations

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#59]
The following methods are declared but not implemented:

* Point()
* Point(double, double)
* set_x(double, double)
* set_y(double, double)

**Comment by mo-c** [comment]
i am really struggling with the classes. Can you create a wiki for me on it.

**Comment by lcabrini** [comment]
Will do.

**Comment by lcabrini** [comment]
I have added a wiki page here: https://github.com/mo-c/moses-cpp-learning/wiki/Creating-a-class
