### ISSUE TITLE
speed: unused and not required function read_double_time()

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#62]
There is a function called read_double_time() which does essentially the same as read_double(). Both functions present a prompt to the user, read in a double value and return that double value. The function read_double_time() does not add anything. Also, it is not used, as can be seen from main(), where read_double() is called twice.

Remove the unneeded/unused function read_double_time(), unless there is a strong argument for its existence. But in that case you also need to use it.

**Comment by mo-c** [comment]
I don't know what the return will be, since i have both distance and time. Moreso i acn not return prompt.
