### ISSUE TITLE
circle-area: create function to read in input from user

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#69]
To make the code easier to follow, create functions where possible. The user input part consists of two things:
1. ask the user for an input
2. read in the input

This can be captured in a single function: prompt user, read in input, return the input

**Comment by mo-c** [comment]
Please check the code for me. i have an error i can not see.

**Comment by lcabrini** [comment]
I get an error trying to run make because it says C++ command not found. Is that your problem? The UNIX C++ compiler is called c++ not C++

**Comment by lcabrini** [comment]
No, I compiled it manually and I've seen the error. Opened a separate issue for it. You can close this issue now.
