### ISSUE TITLE
point: implementation of set_x() and set_y() do not match those in the declaration

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#72]
Please have a look at this wiki page: https://github.com/mo-c/moses-cpp-learning/wiki/Class-attributes,-get-and-set-methods

Then rewrite the methods set_x() and set_y()

**Comment by mo-c** [comment]
Honestly i just started. I did the declaration and did not delete the implementation before i went to bed.However i am pleased with all the issues you raised.

**Comment by lcabrini** [comment]
That is fine. It is my task to find all the problems and raise issues.
