### ISSUE TITLE
point: call to set_x() and set_y() in main() do not match any in class declaration

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#80]
In the declaration of the Point class we have the following:

    void set_x(double);
    void set_y(double);

But, in main() you call:
    p.set_x(4, 3);
    p.set_y(2, 4);

It should be obvious by now, that set_x() and set_y() should only take one parameter each. Ask yourself, after called p.set_x(4, 3), what do you expect the x-coordinate to be: 4 or 3? With p.set_x(-7) it is clear. Only one value is passed in so that will be the value of the x-coordinate.

**Comment by mo-c** [comment]
i sent an uncompleted code. please check it, i have some two errors but don't know how

**Comment by lcabrini** [comment]
Your implementations of set_x() and set_y() are now correct. But you are missing the x() and y() method implementations instead.

The number of methods you implement must equal the number of methods in the class declaration. There are now 6 methods in the declaration (including the ctors), but only four in the implementation.

**Comment by lcabrini** [comment]
You can close this issue as I am opening a new one for the missing methods.
