### ISSUE TITLE
straight-line: create function line_is_horizontal

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#84]
It would be easier to read the code in main() if, instead of

    if (y1 == y2)

you had

    if (line_is_horizontal(y1, y2))

to do this you would have to implement the function line_is_horizontal(). It needs to take both the y-coordinates, since you don't yet have the concept of a line in your code.

**Comment by mo-c** [comment]
Do i create the function outside the main?

**Comment by lcabrini** [comment]
Yes, just as you always do. You cannot create a function inside main(). (Actually, with C++11 you can, sort of, using a lambda function, but more about that later.)

**Comment by mo-c** [comment]
Am i doing for all the conditions in the if statements?

**Comment by lcabrini** [comment]
There is only one condition to determine if the line is horizontal. That is that the two y-coordinates are the same. So all you need to do is create a function that takes y1 and y2 as arguments, returns true if they are equal or false if they are not.

**Comment by mo-c** [comment]
Please check if the function is correct. i Pushed an uncompleted code.

**Comment by lcabrini** [comment]
Are you sure you pushed the code? Because I only see a single function, which is main().

**Comment by mo-c** [comment]
I have pushed it again

**Comment by lcabrini** [comment]
Ok, let's first understand what line_is_horizontal is meant to do. It should receive a pair of (x,y) coordinates. Using this information, it will determine if the line that runs through the two lines is horizontal or not. If the line is horizontal, the function should return true, otherwise false.

Let's summarize this:
1. Pass in (x1, y1) and (x2, y2) to the function. This is what it needs to work with.
2. Return true if the line is horizontal, or false if it is not.

This gives us:
1. The argument list: (double x1, double y1, double x2,, double y2)
2. The return type bool

Now we can create a prototype for the function:

    bool line_is_horizontal(double x1, double y1, double x2, double y2);

To implement this, all you have to do is figure out how to determine if the line (x1, y1)-(x2,y2) is horizontal.and then return true or false as appropriate.

**Comment by mo-c** [comment]
I am still having errors

**Comment by mo-c** [comment]
I have pushed the code

**Comment by lcabrini** [comment]
Worry less about the code in the function for now. Let's start by getting the function prototype right. You need to create a function that takes four double arguments and returns a bool. 

Your current function takes a double (currently not named) and returns a double. This is not correct. Look at my last comment and study the prototype.

The function should take the x and y-coordinates for two points. It should return true if the line is horizontal or false if it is not. That means the return type should be bool, not double.

**Comment by lcabrini** [comment]
This can be closed I think.
