### ISSUE TITLE
create app: args

### ISSUE THREAD

**Issue by lcabrini** [mo-c/moses-cpp-learning#9]
The program should print the number of command-line arguments and list them. For example if the program is run with

% ./args foo bar bim baz quux

Then it should print:
Got 5 command-line arguments. Here they are
1. foo
2. bar
3. bim
4. baz
5. quux

**Comment by mo-c** [comment]
I need help. I have tried to solve it all the codes i tried can not read from the command line.

**Comment by lcabrini** [comment]
You will need this:
argc: holds the number of command-line arguments.
argv: holds the command-line arguments

A special case is argv[0] which holds the name of the program you are running. After that, you have all the command-line arguments, so argv[1] holds the first command-line argument (foo in the above example), argv[2] holds the second command-line argument (bar above) and so on.

**Comment by mo-c** [comment]
i still can not get how it will list and count. i could only get the counting bit of the program.
